project:
  type: website

website:
  title: "Chaeyeon"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: about.qmd
        text: About
      - file: lm.qmd
        text: Language Models

format:
  html:
    theme: cosmo
